const fs = require('fs');
const path = require('path');

// CSS files in the correct order
const cssFiles = [
  'variables.css',
  'base.css',
  'layout.css',
  'buttons.css',
  'app-cards.css',
  'update-section.css',
  'contact-footer.css',
  'progress.css',
  'modals.css',
  'utilities.css'
];

const stylesDir = path.join(__dirname, 'src', 'renderer', 'styles');
const outputFile = path.join(__dirname, 'src', 'renderer', 'styles.css');

let combinedCSS = `/* DriveBox - Main Stylesheet */
/* Auto-generated from modular CSS files */
/* Do not edit this file directly - edit the individual files in /styles/ folder */

`;

// Read and combine all CSS files
cssFiles.forEach(file => {
  const filePath = path.join(stylesDir, file);
  if (fs.existsSync(filePath)) {
    const content = fs.readFileSync(filePath, 'utf8');
    combinedCSS += `/* ===== ${file.toUpperCase()} ===== */\n`;
    combinedCSS += content;
    combinedCSS += '\n\n';
  } else {
    console.warn(`Warning: ${file} not found`);
  }
});

// Write the combined CSS
fs.writeFileSync(outputFile, combinedCSS, 'utf8');
console.log('CSS files combined successfully!');
console.log(`Output: ${outputFile}`);
